name: Destroy given modules of a workspace

on:
  workflow_call:
    inputs:
      infrastructure-repository:
        required: true
        type: string
      workspace-name:
        required: true
        type: string
      modules:
        required: true
    secrets:
      TF_API_TOKEN:
        required: true

jobs:
  create-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout client infrastructure repository
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.infrastructure-repository }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        env:
          TF_WORKSPACE: ${{ inputs.workspace-name }}
        run: |
          terraform init

      - name: Terraform Destroy Module
        run: |
          IFS=',' read -ra MODULES <<< "${{ github.event.inputs.modules }}"
          for MODULE in "${MODULES[@]}"; do
              echo "Removing $MODULE"
              terraform destroy -auto-approve -target="module.$MODULE" || true
          done
