# dependencies :
# Official :
# - actions/checkout@v3 (https://github.com/actions/checkout)
# - actions/setup-node@v3 (https://github.com/actions/checkout)
name: Semantic Release

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: 'lts/*'
      install-dependencies-command:
        required: false
        type: string
        default: 'npm ci'
      cache-dependency-path:
        required: false
        type: string
        default: 'package-lock.json'

    secrets:
      PAT:
        required: true

    outputs:
      version:
        description: 'The next release version'
        value: ${{ jobs.release.outputs.version }}


jobs:
  release:
    name: Release using semantic-release config.
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.latest-release.outputs.version }}

    steps:
      - name: Checkout repo with complete history
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Set up Node.js #does NOT install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: ${{ inputs.package-manager }}
          cache-dependency-path: ${{ inputs.cache-dependency-path }}

      - name: Install dependencies #use cache from previous successful workflow runs if able
        run: ${{ inputs.install-dependencies-command }}

      - name: Release
        id: release
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          npx semantic-release

      - name: Get release version and changelog
        id: latest-release
        run: |
          RELEASE_VERSION=$(gh release list --repo ${{ github.repository }} | head -n 1 | cut -f 2)
          echo "version=$RELEASE_VERSION" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.PAT }}
