name: Semantic Release with Python
  
on:  
  workflow_call:  
    secrets:  
      PAT:  
        required: true 
  
    outputs:  
      version:  
        description: 'The next release version'  
        value: ${{ jobs.release.outputs.version }}  
  
jobs:  
  release:  
    name: Release using python-semantic-release config.  
    runs-on: ubuntu-latest  
  
    outputs:  
      version: ${{ steps.latest-release.outputs.version }}  
  
    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v4  
        with:  
          token: ${{ secrets.PAT }}  
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          
      - name: Release
        id: release
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          npx semantic-release
          
      - name: Get release version  
        id: latest-release  
        run: |  
          RELEASE_VERSION=$(gh release list --repo ${{ github.repository }} | head -n 1 | cut -f 1)         
          echo "version=$RELEASE_VERSION" >> "$GITHUB_ENV"
        env:  
          GH_TOKEN: ${{ secrets.PAT }}
